class World(object):
    def __init__(self):
        self.units = []
        self.rounds = 0
        self.eliminated = []
        self.eliminated_units = []
        self.eliminated_units_names = []
        self.eliminated_units_hp = []
        self.eliminated_units_damage = []
        self.eliminated_units_rounds = []
        self.eliminated_units_dead_rounds = []
        self.eliminated_units_dead_rounds_total = []
        self.eliminated_units_dead_rounds_average = []
        self.eliminated_units_dead_rounds_average_round = []
        self.eliminated_units_dead_rounds_average_round_total = []
        self.eliminated_units_dead_rounds_average_round_average = []
        self.eliminated_units_dead_rounds_average_round_average_round = []
        self.eliminated_units_dead_rounds_average_round_average_round_total = []
        self.eliminated_units_dead_rounds_average_round_average_round_average = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round_total = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round_average = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round_average_round = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round_average_round_total = []
        self.eliminated_units_dead_rounds_average_round_average_round_average_round_average_round_average = []
        self.eliminated_units_dead_rounds_average_round_average_round_ = []